// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAdbInfo() {
  return window['go']['main']['App']['GetAdbInfo']();
}

export function InstallApk(arg1) {
  return window['go']['main']['App']['InstallApk'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function SelectApk() {
  return window['go']['main']['App']['SelectApk']();
}
