// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelApk():Promise<boolean>;

export function GetAdbInfo():Promise<main.AdbInfo>;

export function InstallApk(arg1:main.InstallRequest):Promise<main.InstallResult>;

export function ListDevices():Promise<Array<main.Device>>;

export function SelectApk():Promise<string>;
